apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "calico-auto-policy.fullname" . }}
  labels:
    {{- include "calico-auto-policy.labels" . | nindent 4 }}
data:
  policy.yaml: |
    {{- .Values.policy | toYaml | nindent 4 }}
