{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "calico-auto-policy.serviceAccountName" . }}
  labels:
    {{- include "calico-auto-policy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "calico-auto-policy.serviceAccountName" . }}
  labels:
    {{- include "calico-auto-policy.labels" . | nindent 4 }}
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["crd.projectcalico.org"]
    resources: ["networkpolicies"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "calico-auto-policy.serviceAccountName" . }}
  labels:
    {{- include "calico-auto-policy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "calico-auto-policy.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace | quote }}
    name: {{ include "calico-auto-policy.serviceAccountName" . }}
{{- end }}
