apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: default
  namespace: default
spec:
  order: 1400
  selector: all()
  types:
    - Egress
  egress:
    # Deny all
    - action: Deny
